#!/usr/bin/env python3
"""Generate the `initial/` board dataset.

A Catan board is fully determined by its integer `seed` (Catanatron shuffles
resources/ports off the global RNG seeded by that value; with the default
`official_spiral` number placement the numbers stay on the canonical spiral and
only resources/ports vary). The seed is therefore the source of truth: every
board state file records its seed and can be regenerated byte-for-byte from it.

We still serialize a compact, human-readable static layout (tiles + ports +
robber) plus the board fingerprint so files are self-contained and verifiable
without re-running Catanatron. The fingerprint matches
`harness.runner._board_fingerprint`, so a dataset board and a runner board for
the same seed PROVABLY share a layout.

Layout produced:

    dataset/
      initial/
        index.json            # manifest: params + per-split board lists
        init_0000.json        # one board state file per board
        init_0001.json
        ...

Later, env-generation steps write their own sibling subfolders under dataset/
(e.g. dataset/<env_name>/) using the same board-state-file schema.

Each board is one seed, played as a mirrored seat-swap PAIR at run time (the seed
fixes the board; the runner swaps RED/BLUE for the two orientations) -- so "1 seed
per board (x2)".

Splits reflect how a board is used, pre-assigned by a deterministic shuffle keyed
on `--meta-seed` (reproducible, independent of file order):
  * grader_games -- seeds for the full self-play games the grader runs on
    (play the game out from this board, then grade it). Default 100 boards.
  * example_pool -- boards to mine specific mid-game states from (e.g. opening
    placements): load the board, advance to a state, ask the model to act. The
    remainder of `--count`.
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # repo root on path

from catanatron.game import Game
from catanatron.json import GameEncoder
from catanatron.models.player import Color, SimplePlayer

from harness.runner import _board_fingerprint

SCHEMA_VERSION = 1
# Match the runner's 1v1 board construction exactly: two players, RED then BLUE.
# Board generation consumes the global RNG identically regardless of player type,
# so a dataset board for seed S == the runner's board for seed S.
_PLAYERS = lambda: [SimplePlayer(Color.RED), SimplePlayer(Color.BLUE)]


def _coord(c) -> list:
    """Cube coordinate tuple -> JSON-friendly list."""
    return list(c) if c is not None else None


def _val(x):
    """Catanatron resources/directions are sometimes Enums, sometimes plain str."""
    if x is None:
        return None
    return getattr(x, "value", x)


def build_board_record(seed: int, number_placement: str, vps_to_win: int) -> dict:
    """Construct one board from a seed and snapshot its static layout."""
    game = Game(
        _PLAYERS(),
        seed=seed,
        vps_to_win=vps_to_win,
        number_placement=number_placement,
    )
    board = game.state.board

    land = []
    for coordinate, tile in board.map.land_tiles.items():
        if tile.resource is None:
            land.append({"id": tile.id, "coordinate": _coord(coordinate),
                         "type": "DESERT", "resource": None, "number": None})
        else:
            land.append({"id": tile.id, "coordinate": _coord(coordinate),
                         "type": "RESOURCE_TILE", "resource": _val(tile.resource),
                         "number": tile.number})
    land.sort(key=lambda t: t["id"])

    ports = []
    for pid, port in board.map.ports_by_id.items():
        ports.append({
            "id": pid,
            "resource": _val(port.resource),  # None == 3:1
            "direction": _val(port.direction),
            "nodes": sorted(port.nodes.values()),
        })
    ports.sort(key=lambda p: p["id"])

    # Full serialized fresh state (state_index 0): a ready-to-load starting point
    # for example-mining, so downstream code need not re-run Catanatron from the
    # seed. Regenerable from `seed` -- kept for convenience and verification.
    initial_state = json.loads(json.dumps(game, cls=GameEncoder))

    return {
        "schema_version": SCHEMA_VERSION,
        "seed": seed,
        "number_placement": number_placement,
        "map_template": "BASE",
        "vps_to_win": vps_to_win,
        "board_fingerprint": _board_fingerprint(game),
        "robber_coordinate": _coord(board.robber_coordinate),
        "tiles": land,
        "ports": ports,
        "initial_state": initial_state,
    }


def assign_splits(board_ids: list[str], n_grader: int, meta_seed: int) -> dict[str, str]:
    """Deterministically map each board_id -> split via a meta-seeded shuffle.

    First `n_grader` shuffled boards -> grader_games; the rest -> example_pool.
    """
    rng = random.Random(meta_seed)
    shuffled = board_ids[:]
    rng.shuffle(shuffled)
    return {
        bid: ("grader_games" if i < n_grader else "example_pool")
        for i, bid in enumerate(shuffled)
    }


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate the initial/ board dataset.")
    ap.add_argument("--count", type=int, default=400, help="number of boards (default 400)")
    ap.add_argument("--start-seed", type=int, default=1000, help="first seed (inclusive)")
    ap.add_argument("--number-placement", default="official_spiral",
                    choices=["official_spiral", "random"])
    ap.add_argument("--vps-to-win", type=int, default=10)
    ap.add_argument("--out", default="dataset/initial", help="output directory")
    ap.add_argument("--meta-seed", type=int, default=20260620,
                    help="seed for the grader/example split shuffle")
    ap.add_argument("--grader-games", type=int, default=100,
                    help="number of boards used as grader self-play games (rest -> example_pool)")
    args = ap.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    seeds = list(range(args.start_seed, args.start_seed + args.count))
    board_ids = [f"init_{i:04d}" for i in range(args.count)]
    splits = assign_splits(board_ids, args.grader_games, args.meta_seed)

    fingerprints: dict[str, str] = {}
    manifest_boards = []
    collisions = 0

    for bid, seed in zip(board_ids, seeds):
        rec = build_board_record(seed, args.number_placement, args.vps_to_win)
        rec["board_id"] = bid
        rec["split"] = splits[bid]

        fp = rec["board_fingerprint"]
        if fp in fingerprints:
            collisions += 1
            print(f"  ! duplicate layout: {bid} (seed {seed}) == {fingerprints[fp]} [{fp}]")
        else:
            fingerprints[fp] = bid

        (out_dir / f"{bid}.json").write_text(json.dumps(rec, cls=GameEncoder, indent=2))
        manifest_boards.append({"board_id": bid, "seed": seed,
                                "split": rec["split"], "board_fingerprint": fp})

    split_counts: dict[str, int] = {}
    for b in manifest_boards:
        split_counts[b["split"]] = split_counts.get(b["split"], 0) + 1

    manifest = {
        "schema_version": SCHEMA_VERSION,
        "kind": "initial",
        "count": args.count,
        "start_seed": args.start_seed,
        "number_placement": args.number_placement,
        "vps_to_win": args.vps_to_win,
        "grader_games": args.grader_games,
        "meta_seed": args.meta_seed,
        "split_counts": split_counts,
        "unique_layouts": len(fingerprints),
        "duplicate_layouts": collisions,
        "boards": manifest_boards,
    }
    (out_dir / "index.json").write_text(json.dumps(manifest, indent=2))

    print(f"Wrote {args.count} boards to {out_dir}/")
    print(f"  splits: {split_counts}")
    print(f"  unique layouts: {len(fingerprints)}  (duplicates: {collisions})")


if __name__ == "__main__":
    main()
